### ISSUE TITLE
Draft: Layout changes to smooth up the style

### ISSUE THREAD

**Issue by danopolan** [istqborg/istqb_product_base#10]
TODOs:

1. [x] Remove the header and footer from the landing page. The first page will be the one after the landing page.
2. [x] Add a `code` from metadata in the first line of the header so it will be: ISTQB® Certified Tester Foundation Level (CTFL)
3. [ ] Add Copyright in the footer into the box with a page number. Ideally, centred below it. 
4. [ ] Make body text smaller by 1 point
7. [ ] Place ISTQB logos in `istqb_template` repo so it can be changed for every product
8. [x] add support for email links like `[translation@castb.org](mailto:translation@castb.org)`. Currently, it's generating the following
![image](https://github.com/istqborg/istqb_product_base/assets/95688217/beb5d4f0-3452-4c34-a58c-96ecc44b5e86)
10. [x] add the ability to add section reference to _References_ and _Further reading_ chapters
11. [x] add support for Contents, References, Further Reading, List of Tables, List of Images, Index, Section references in text in languages other than English (Czech and Slovak for now)
12. [x] do not split questions over more pages
![image](https://github.com/istqborg/istqb_product_base/assets/95688217/6747c094-806a-46b9-ad49-aa39b13e2eb0)

**Comment by Witiko** [comment]
> How we can approach the implementation? Meaning how to split it into Issues.

Here is how I would split the issue:

- TODOs 1, 2, 3, 4, and 9 are style changes. There may be back-and-forth based on personal taste and designer feedback.
- TODOs 6, 7, and 8 are additions to document markup that will need to be documented in `example-document.tex`.
- TODO 5 belongs to the repository `istqborg/istqb_product_template`.

However, I can finish each TODO in a couple minutes. Therefore, it does not seem very helpful to split this issue into several.

> 5. Place ISTQB logos in `istqb_template` repo so it can be changed for every product.

For every product, you can add a new logo to the directory `img/` and then use it from the document metadata. The logo is first searched in the product `img/`directory and, if it does not exist in there, then in the directory `img/` of the repository `istqborg/istqb_product_base`. You can add a copy of the file `istqb-logo-default.png` to the repository `istqborg/istqb_product_template` if you think that's more intuitive to users. However, the file `istqb-logo-default.png` needs to stay in the repository `istqborg/istqb_product_base` also, because it is used from the document `example-document.tex`.

> 6. add support for email links like `[translation@castb.org](mailto:translation@castb.org)`.

You can just type `<translation@castb.org>`. This will produce a clickable link. Writing `[translation@castb.org](mailto:translation@castb.org)` should produce the same result but currently does not; I track the issue in https://github.com/Witiko/markdown/issues/424 and I will fix by the end of the month.

**Comment by Witiko** [comment]
> implement everything except 4 for now

TODO 3 (add copyright into page number box) also has the potential to affect page breaks, especially if you'd like me to remove the current box with the copytight. Is it important for you that TODO 3 is fixed in a way that keeps the type area and the page breaks the same as they are now? Can you please sketch out for me how you would like the footer to look? MS paint over a screenshot of how the footer currently looks should work fine in the absence of a designer spec.

**Comment by danopolan** [comment]
We do not have any finally reviewed documents, so these changes are not breaking any production documents.
Anyway, I would skip 3 and 4 for now. We need to think about the style in higher level. I will be in touch with ISTQB and graphic designers to resolve this and propose complex changes with sketches later.

**Comment by Witiko** [comment]
I will in the following two weeks unless you'd like them earlier. For the moment, please use whatever markup that you find appropriate in your markdown documents and @ping me from the corresponding PRs, so that I can fix your markup when I have finished the documentation / implementation of the PRs.

**Comment by Witiko** [comment]
Here are other tickets and PRs that are related to points 7 and 8 from the original post:

- https://github.com/istqborg/istqb_ctfl/pull/8#issuecomment-2034419247

**Comment by Witiko** [comment]
@danopolan I will tackle the following point tomorrow:

> - [ ] add support for Contents, References, Further Reading, List of Tables, List of Images, Index, Section references in text in languages other than English (Czech and Slovak for now)

I am thinking of adding a new optional metadata key `language` that would contain the (main) language of the document: `cs`, `sk`, or `en`. If the key is not specified, the default value `en` would be assumed. Setting the metadata key would automatically localize all section names, section/image/table references in text, and also hyphenation. Please, let me know if any of this seemed off before I start the implementation tomorrow afternoon.

**Comment by danopolan** [comment]
This is exactly what I thought. So sure, having new key `language` would be the best.

**Comment by Witiko** [comment]
In https://github.com/istqborg/istqb_product_base/pull/42, I opened a draft PR that will eventually add support for Czech and Slovak product documents from point 9 in this ticket:

> - [ ]  add support for Contents, References, Further Reading, List of Tables, List of Images, Index, Section references in text in languages other than English (Czech and Slovak for now)

During my work on the point, I realized that besides the above tasks, we also need to localize the automatically generated texts on the landing page and the page head and foot. Furthermore, I discovered some further design consideration that we need to iron out, which I describe below:

Writing `<#section:...>`, `<#figure:...>`, and `<#table:...>` is ambiguous in flective languages such as Czech and Slovak, where the generated label should differ based on the current grammatical case. For example, `jak ukazuje <#table:procesy>` should become "jak ukazuje Tabulka 1", whereas `vizte <#table:procesy>` should become "vizte Tabulku 1", and `v <#table:procesy>` should become "v Tabulce 1".

Here is a number of possible solutions:

1. Have `<#...>` produce only the section/figure/table number. Authors would write `vizte Tabulku <#table:procesy>`.
    This would require us to add labels before `<#...>` in all existing documents.
2. Support localized prefixes such as `jak ukazuje <#tabulka:procesy>`, `vizte <#tabulku:procesy>`, `v <#tabulce:procesy>`.
    This would require us to update all labels in https://github.com/istqborg/istqb_ctfl/pull/8#issuecomment-2034419247 and https://github.com/istqborg/istqb_ctfl/pull/9. Furthermore, this would also require us to roll back the addition of `<#references>` and `<#further-reading>` in https://github.com/istqborg/istqb_product_base/pull/37 and replacing them with `<#...:references>` and `<#...:further-reading>`, where `...` would be a localized prefix.
3. Default to the accusative case, which appears most commonly in https://github.com/istqborg/istqb_ctfl/pull/8#issuecomment-2034419247 and https://github.com/istqborg/istqb_ctfl/pull/9, and translate `vizte <#table:procesy>` to "vizte Tabulku 1". When other grammatical cases are needed, authors can write ```jak ukazuje [Tabulka `\ref{table:procesy}`{=tex}](#table:procesy)``` or ```v [Tabulce `\ref{table:procesy}`{=tex}](#table:procesy)```.

Solution 1 is easy to implement but leads to more redundant and less readable source code and will require a great many changes to existing documents. Solution 2 leads to a highly-readable source code but will require many changes to the code and existing documents. Solution 3 leads to very difficult-to-read code for grammatical cases other than the accusative case but requires few changes to the code and existing documents.

Personally, I like solution 2 the most. @danopolan, please let me know which solution you like the best.

**Comment by Witiko** [comment]
As discussed with @danopolan today, we will want to go with solution 3 for now.
