### ISSUE TITLE
General text translations for Syllabus and Exam documents

### ISSUE THREAD

**Issue by danopolan** [istqborg/istqb_product_base#122]
To fully support other languages, we need to add macros for following keys. Examples for German are provided, but support for Slovak and Czech should be added as well.

Syllabus document

~~copyright => Urheberschutzvermerk~~ this is in MD files
~~acknowledgments => Danksagung~~ this is in MD files
~~revision history => Änderungsübersicht~~ this is in MD files
~~figure => Abbildung~~ already defined

Sample exams document

Answer Key = Lösungsschlüssel
Answers =  Antworten
Question = Frage
Answer Key = Lösungsschlüssel
Fragenummer | korrekte Antwort | Lernziele | K-Level | Punkteanzahl
Explanation / Rationale = Begründung
Questions = Fragen
Question = Frage
Point = Punkt
Points = Punkte
Select TWO Options = Wählen Sie genau ZWEI Optionen
Select ONE Option = Wähle Sie genau EINE Option

![Screenshot_20241030-170923](https://github.com/user-attachments/assets/e5740f4b-eda2-4235-aa9a-756cc01286cb)

**Comment by Witiko** [comment]
> ### Syllabus document
> copyright => Urheberschutzvermerk
> acknowledgments => Danksagung
> revision history => Änderungsübersicht

> To fully support other languages, we need to add macros for following keys.

I am confused; are you suggesting that we 1) produce the above translations in the automatically generated parts of the documents or that we 2) provide a way for users to input the above texts in the markdown files?

If it's 1), then I don't see where the texts "copyright", "acknowledgments", and "revision history" appear in automatically generated text. As far as I can see, these texts only appear in the markdown text. If it's 2), would you be happy with reusing the syntax for variables such as `${language.variables.copyright}` to include the value of the (currently non-existent) key `variable.copyright` from the current language file such as `languages/de.yml`? However, how is this helpful if the rest of the markdown text still has to be translated by a (German) person who can likely type "Urheberschutzvermerk" easier than they can recall and type `${language.variables.copyright}`?

> figure => Abbildung

In commit 85c8ae7 from the PR-less branch `feat/syllabus-and-exam-documents-general-text-translations`, I translated the labels of figures and also tables (Table => Tabelle):

![image](https://github.com/user-attachments/assets/dfb77dae-b7c1-4443-b6a1-c0e9eeda7a9e)
![image](https://github.com/user-attachments/assets/70031d2e-b2b6-47ad-bdcf-c1b554322737)

> ### Sample exams document

In commit 34df73c from the PR-less branch `feat/syllabus-and-exam-documents-general-text-translations`, I translated most parts of the sample exam documents:

https://github.com/istqborg/istqb_product_base/blob/34df73c5b8d8391fa35acca300b8258ca39a44d0/languages/de.yml#L16-L29

Besides German, I also added Czech and Slovak translations. Later today, I will implement the translations, so that they appear in the sample exam documents.

Here is the only part that I did not translate:

> Sample Exam – Questions => Probeprüfung – Fragen

I will translate the "– Questions" (and "– Answers") part of the landing page, since it has been automatically generated. However, the "Sample Exam" part of the title page is not automatically generated but originates from the key `type` of the file `metadata.yml`. You should type "Probeprüfung" directly in the file `metadata.yml` to translate it. Alternatively, we can make it so that sample exam documents ignore the key `type` and always use a translation of "Sample Exam" instead.

**Comment by danopolan** [comment]
Sorry for the confusion. We are talking only about text which is generated, so it has to be defined in `./languages/*.yml` files. All the text provided in the Markdown files can be ignored. I have edited the task. This was communicated to a German team already via email; I just did not reflect it here when I was copying their complaint into an issue.

**Comment by Witiko** [comment]
Not a problem! I implemented the translations in PR https://github.com/istqborg/istqb_product_base/pull/125. See https://github.com/istqborg/istqb_product_base/pull/125#issuecomment-2452511572 for a demonstration.
