### ISSUE TITLE
Encoding of 0xa9 fails in CTFL SK Errata

### ISSUE THREAD

**Issue by danopolan** [istqborg/istqb_product_base#142]
We have encountered a failure with CTFL SK build with error `UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa9 in position 69745: invalid start byte`.

https://github.com/istqborg/istqb-ctfl/actions/runs/11794261815/job/32851542285

PR https://github.com/istqborg/istqb-ctfl/pull/23/ has only one change on `0xa9` character, so I do not understand why this is popping up and why the build fails on this character.

**Comment by Witiko** [comment]
The issue is unrelated to https://github.com/istqborg/istqb-ctfl/pull/23 and caused by the changes to the template from https://github.com/istqborg/istqb_product_base/pull/141, where we started validating BIB entries based on the output of TeX in LOG files. LOG files can contain all sorts of noise, even standalone bytes that don't conform to the UTF-8 text encoding. Therefore, I made the validation more robust in commit f601912 by ignoring such bytes. [This fixes the build.][1]

 [1]: https://github.com/istqborg/istqb-ctfl/actions/runs/11794261815
