### ISSUE TITLE
Update files generated by the CI

### ISSUE THREAD

**Issue by danopolan** [istqborg/istqb_product_base#52]
We would need to update the CI so that the names of the generated files will be based on the `metadata.yml` file.

Documents should be named based on the format `ISTQB-<code>-<type>-<version>` so, e.g. `ISTQB-CTAL-TA-Syllabus-v4.0.`

We can possibly add an extra parameter for the filename or other shortcut, but this will just duplicate the data and possibly cause errors.

**Comment by Witiko** [comment]
This seems tricky, especially since it's not always clear which metadata file belongs to which document without compiling them first, see e.g. documents `sample-exam-questions-*.tex` and `sample-exam-answers-*.tex` in repository [`istqborg/istqb-ctfl`][1]. Can we try this for PDF documents first and perhaps expand it to other types of documents later?

 [1]: https://github.com/istqborg/istqb-ctfl
