### ISSUE TITLE
Markdown tables overflowing the page

### ISSUE THREAD

**Issue by danopolan** [istqborg/istqb_product_base#60]
As discussed in #51 [comment](https://github.com/istqborg/istqb_product_base/issues/51#issuecomment-2145477563), I am still facing the issue in [CTFL](https://github.com/istqborg/istqb-ctfl/actions/runs/9158874602) (section 0.12) as [CTAL-TA](https://github.com/istqborg/istqb-ctal-ta/actions/runs/9406031719) (appendix A, chapter 4, section 0.4).

I am following the documentation, but still not getting the expected results where tables should be respecting page margins as the text does.

![image](https://github.com/istqborg/istqb_product_base/assets/95688217/a53abede-845f-4a79-9381-8bad1e413c6f)

**Comment by Witiko** [comment]
As discussed in https://github.com/istqborg/istqb_product_base/issues/51#issuecomment-2145477563, the issue in CTFL is not present in branch `main`. Looking at the run https://github.com/istqborg/istqb-ctfl/actions/runs/9158874602, it seems that the issue is only present in branch `ctfl-sk-fixes`. I looked though the commits in the branch and I located the source of the issue in commit 1a1b16f:

``` diff
  | **Skratka** | **Význam** | **Slovenský význam** |
- | ----------- | ---------- | -------------------- |
+ | ----------: | :--------- | :------------------- |
  | ISTQB | International Software Qualifications Board | Medzinárodný výbor pre testovanie softvéru |
  | CTFL | Certified Tester Foundation Level | Certifikovaný tester základnej úrovne |
  | SDLC | software development lifecycle | životný cyklus vývoja softvéru |
```

The issue is that only the specifier `----` makes the column fill all remaining page width and wraps the content of the cells. The other specifiers (`:---`, `:--:`, and `---:`) makes the column only occupy as much page width as necessary and the content of the cells doesn't wrap. The specifier `---` is intended to be used for columns, where cells may contain paragraphs of text, whereas the other specifiers are intended to be used for short text cells.

In the above example from CTFL, you should replace the specifiers `:---------` and `:-------------------` for columns 2 and 3 with specifiers `----------` and `--------------------`, as before commit 1a1b16f. This will cause the table to correctly wrap. I haven't looked at the code for CTAL-TA but I assume the issue will be similar.

> I am following the documentation [...]

I apologize that the documentation is not very clear on the wrapping behavior. I can update the documentation to be clearer about the distinction between the specifier `----` versus the other specifiers with respect to wrapping.

**Comment by danopolan** [comment]
Please update the documentation to be more specific how to setup tables and how to resolve tables overflowing the page.
