### ISSUE TITLE
CTAL TA Sample Exam critical issues

### ISSUE THREAD

**Issue by danopolan** [istqborg/istqb_product_base#63]
We did not check Sample Exam for CTAL TA for some time and found several major issues in formatting.

1. ONE option is indicated instead of TWO. This was changes in #29 but doesn't work. Affected are questions 13 and 26.
![image](https://github.com/istqborg/istqb_product_base/assets/95688217/e85e42d7-bcc5-49f6-803f-c09801393b63)

2. Questions text overlap with a footer for questions 14 and 20. This is cause by not splitting questions across more pages, but we could lower top margin so the question starts higher and make tables bit smaller.
![image](https://github.com/istqborg/istqb_product_base/assets/95688217/278acebd-3e46-44b3-87ee-dcdbff909aaa)

3. Answers explanation is a mess
![image](https://github.com/istqborg/istqb_product_base/assets/95688217/f10aac8a-017c-4472-ab3f-9eb7dbd2dfe4)

**Comment by Witiko** [comment]
I assume this is related to https://github.com/istqborg/istqb-ctal-ta/pull/4.

> 1. ONE option is indicated instead of TWO. Affected are questions 13 and 26.

This is due to an error in the input data, please see my review comments in https://github.com/istqborg/istqb-ctal-ta/pull/4:
- https://github.com/istqborg/istqb-ctal-ta/pull/4/files#r1632221807
- https://github.com/istqborg/istqb-ctal-ta/pull/4/files#r1632221848

As I offered in https://github.com/istqborg/istqb_product_base/issues/29#issuecomment-2098057295, I can strengthen the validation by requiring two correct answers for questions with five possible answers. This would allow us to catch such errors early. Furthermore, we may want to make the template smarter, so that it can understand both `correct: [a, b]` and `correct: a, b` even though the former is a YAML list and the latter is just text.

> 2. Questions text overlap with a footer for questions 14 and 20. This is cause by not splitting questions across more pages, but we could lower top margin so the question starts higher and make tables bit smaller.

We anticipated this issue in https://github.com/istqborg/istqb_product_base/pull/38#issuecomment-2061994798 and already discussed a possible solution. I will take a look at implementing it on Monday at the latest.

> 3. Answers explanation is a mess.

The [results][1] of CI for commit https://github.com/istqborg/istqb_product_template/commit/adf5fc21f10417196d29e8ca0a34671dee084030 from May 3 contain answer explanations that look OK:

![image](https://github.com/istqborg/istqb_product_base/assets/603082/2ddb039f-32fe-4b97-b635-1a9d6e4656f2)

By contrast, the [results][2] of CI for commit https://github.com/istqborg/istqb_product_template/commit/c09debd622cd10d29e7e474b577a6893456ad641 from today contain no questions or answers:

![image](https://github.com/istqborg/istqb_product_base/assets/603082/dd406001-e004-4772-90b9-72c372dbb47b)

This indicates that there is a larger issue or possibly several issues at play, not just an issue with typesetting answer explanations.

Regardless, the issues seem to be regressions that have occurred in this repository since or after May 3, i.e. between commits 73d6e91e4191fe9126d2a32e26c99b6d79f903e1 and 4793179cf7fd92862050740280e1fd0d41a6d104. I will take a look at finding the regressions and fixing them on Monday.

 [1]: https://github.com/istqborg/istqb_product_template/actions/runs/8935315149
 [2]: https://github.com/istqborg/istqb_product_template/actions/runs/9435753009

**Comment by Witiko** [comment]
> This indicates that there is a larger issue or possibly several issues at play, not just an issue with typesetting answer explanations.

After applying the fix from commit https://github.com/istqborg/istqb_product_base/pull/64/commits/ea5fee1e4e39f7b1607d1ae11cadb61526bcf96e in PR https://github.com/istqborg/istqb_product_base/pull/64, the results of CI for commit https://github.com/istqborg/istqb_product_template/commit/c09debd622cd10d29e7e474b577a6893456ad641 from today look as follows:

![image](https://github.com/istqborg/istqb_product_base/assets/603082/defaa9f9-9092-4128-a195-890e70fee290)

This reproduces the issue from point 3 in the original post.
