### ISSUE TITLE
Table borders are not shown properly in some viewers

### ISSUE THREAD

**Issue by danopolan** [istqborg/istqb_product_base#69]
Some viewers do not render tables correctly in PDF documents. This also depends on the zoom used in a specific viewer.

I am using CTAL TA Sample Question 14 as an example, but this issue is shared across different documents. Tables defined in Markdown that are part of the syllabus or questions content are most affected.

Can you please investigate the cause and possible fixes? In some cases, it's just a visual thing, but for example, in Question 14 of CTAL TA, table borders are crucial for correctly understanding the decision table.

Can we include lowering cell margins by one or two points if possible? Currently, tables are taking up quite a lot of space on the page.

Chrome
![chrome](https://github.com/istqborg/istqb_product_base/assets/95688217/b4cd4dd6-9ef3-456b-bbad-86b7190ba9a1)

Firefox
![firefox](https://github.com/istqborg/istqb_product_base/assets/95688217/abe28595-11ca-4bd0-a91a-5750fab6ab93)

Foxit Reader
![foxit](https://github.com/istqborg/istqb_product_base/assets/95688217/c7b0262d-cf31-4882-b64c-8fb3626d296c)

Acrobat Reader
![acrobat](https://github.com/istqborg/istqb_product_base/assets/95688217/b0f05319-6f85-4fa2-b4ec-bbedb09cb3db)

**Comment by Witiko** [comment]
I can reproduce your issues in a Windows 11 VM:

![image](https://github.com/user-attachments/assets/fedae6dc-b0ac-44dd-a2ff-88fc34c5f141)

The issue is ultimately with the viewer which fails to properly render subpixels. This is especially egregious with Adobe Reader. However, we should be able to improve the rendering by not rendering white backgrounds and by rendering lines above backgrounds, not below them. Here is some relevant discussion on the topic:

- [Solution for disappearing table/cell borders with \rowcolor in the PDF viewer depending on zoom?](https://tex.stackexchange.com/questions/490663/solution-for-disappearing-table-cell-borders-with-rowcolor-in-the-pdf-viewer-de)
- [mdframed missing half the frame](https://tex.stackexchange.com/questions/124539/mdframed-missing-half-the-frame)

Furthermore, in addition to reducing the cell margins, as requested in https://github.com/istqborg/istqb_product_base/issues/69#issue-2345668683, we can also slightly increase the line thickness, although this should perhaps be unnecessary.
